### ISSUE TITLE
flashing lights with baked light data. 

### ISSUE THREAD

**Issue by gostbento** [RetroGEO/reroStandard#6]
maybe I am stupid, maybe I have done something wrong but one I bake the lighting this happens. (video) 
All materials on map use reroStandard on the video

https://user-images.githubusercontent.com/44307374/149801954-d4a86806-cff5-40d6-b193-185e127a7f12.mp4

I say "in and out of existence" which is not the case but the lights are flashing. 
thanks for the help

**Comment by Shanesan** [comment]
The issue here is mixed lighting. You are allowed I believe 6 real-time lights (which includes mixed lights) and then you get flickering. Saying this, _never_ use mixed lighting or real-time lighting, it's very expensive.

If you want artificial lights, bake them, add effects to make it look like they're actually lighting up an area (like bugs or whatever), and utilize light probes to illuminate characters that cast under it.

**Comment by gostbento** [comment]
thanks, this issue was solved.
